import React from 'react';
import { Container, Row, Col, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';

import { renderInputReactstrap } from '../../../form-helpers/renderInputTextFields';
import Button from '../../../components/styled-components/Button';
import { Card } from '../../../components/styled-components/Divs';
import { Small, Wrap, P } from '../../../components/styled-components/Typography/headers';
import Guides from './Guides';

const Setup2FA = props => {
  const { secret, modal, generateKey, verifyCode, toggleModal } = props;

  return (
    <div>
      <Container>
        <Row>
          <Col className="text-center">
            <div className="m-t-50">
              <img src="./img/img-2FA-setup.png" alt="2FA Setup" width={260} />
            </div>
            <h1 className="grey-title m-t-30 m-b-50">Please setup 2-factor authentication</h1>
            <P opacity={0.8}>
              2-factor authentication (2FA) is a reliable and simple way to keep the account safe. <br/> 
              Security is in high priority for us, so we ensure that all users setup 2FA.
            </P>
          </Col>
        </Row>
      </Container>
      <Guides />
      <Container>
        <Row>
          <Col className="text-center m-b-40">
            { !secret &&
              <div className="m-t-40">
                <Button primary
                  onClick={e => {
                    e.preventDefault();
                    generateKey();
                  }}
                >
                  Generate key
                </Button>
              </div>
            }

            { secret &&
              <Col lg={{ size: '8', offset: '2' }} className="m-t-40">
                <Card align="left">
                  <Row>
                    <Col lg={8}>
                      <p className="m-b-20">Add a new account at authentication app and scan the QR-code or enter the key below manually.</p>
                      <span>Enter this key:</span>
                      <Wrap>{ secret.string }</Wrap>
                    </Col>
                    <Col lg={4} className="text-center">
                      <span>QR-code:</span>
                      <img
                        src={secret.img}
                        alt="QR code for your 2FA secret key"
                      />
                    </Col>
                  </Row>
                </Card>
                <Button primary className="m-t-40" onClick={toggleModal}>
                  Done
                </Button>
                <div className="m-t-30">
                  <Small opacity={0.7}>Had problems with setup? Please check our tutorials</Small>
                  <Small><a href="https://support.google.com/accounts/answer/1066447?co=GENIE.Platform%3DAndroid&hl=en" target="_blank">Tutorial for Google Authenticator</a></Small>
                  <Small><a href="https://support.authy.com/hc/en-us" target="_blank">Tutorial for Authy</a></Small>
                </div>
              </Col>
            }
          </Col>
        </Row>
        <Modal isOpen={modal} toggle={toggleModal} className="custom">
          <form className="form"
              onSubmit={e => {
                e.preventDefault();
                verifyCode(e.target.code.value);
              }}
            >
            <ModalHeader toggle={toggleModal}>Finish 2-factor Authentication setup</ModalHeader>
            <ModalBody>
              <Row>
                <Col sm={9} xs={8}>
                  <p>Now, try it in use.</p>
                  <p>Please enter the 6-digit code generated by the authentication app on your device to finish 2FA setup.</p>
                  <div className="form-group m-t-10">
                    <label><small>Authentication code</small></label>
                    <input className="form-control" placeholder="" type="text" name="code" maxLength="6" />
                    <Small opacity="0.7" className="pull-right m-t-5">Example: 123456</Small>
                  </div>
                </Col>
                <Col sm={3} xs={4} className="text-center">
                  <img src="./img/img-2FA-device.png" className="m-t-30" alt="2FA Setup Device" width={60} />
                </Col>
              </Row>
            </ModalBody>
            <ModalFooter className="justify-content-center">
              <Button primary>Finish</Button>
            </ModalFooter>
          </form>
        </Modal>
      </Container>
    </div>
  );
};

export default Setup2FA;
